export const COURT_VISUAL_GEOMETRY = {
  centerLaneLeftPercent: 33.33,
  centerLaneWidthPercent: 33.34,
  laneOneLeftPercent: 33.33,
  laneTwoLeftPercent: 66.66,
  frameAreaWidthPercent: 18,
  forbiddenAreaTopPercent: 10,
  forbiddenAreaWidthPercent: 52,
  forbiddenAreaHeightPercent: 80,
  forbiddenAreaOffsetPercent: -26,
  degreeGuideWidthPercent: 27,
  horizontalTopPercent: 25,
  horizontalMiddlePercent: 50,
  horizontalBottomPercent: 75,
} as const;
